const menu = [
  {
    id: 1,
    name: "French Toast",
    desc: "Crispy * gooney French toast made with chaaye khana's very own bread",
    price: 490,
    img: "./images/item-1.jpeg",
  },
  {
    id: 2,
    name: "French Toast",
    desc: "Crispy * gooney French toast made with chaaye khana's very own bread",
    price: 490,
    img: "./images/item-2.jpeg",
  },
  {
    id: 3,
    name: "French Toast",
    desc: "Crispy * gooney French toast made with chaaye khana's very own bread",
    price: 490,
    img: "./images/item-3.jpeg",
  },
  {
    id: 4,
    name: "French Toast",
    desc: "Crispy * gooney French toast made with chaaye khana's very own bread",
    price: 490,
    img: "./images/item-4.jpeg",
  },
  {
    id: 5,
    name: "French Toast",
    desc: "Crispy * gooney French toast made with chaaye khana's very own bread",
    price: 490,
    img: "./images/item-5.jpeg",
  },
  {
    id: 6,
    name: "French Toast",
    desc: "Crispy * gooney French toast made with chaaye khana's very own bread",
    price: 490,
    img: "./images/item-6.jpeg",
  },
  {
    id: 7,
    name: "French Toast",
    desc: "Crispy * gooney French toast made with chaaye khana's very own bread",
    price: 490,
    img: "./images/item-7.jpeg",
  },
  {
    id: 8,
    name: "French Toast",
    desc: "Crispy * gooney French toast made with chaaye khana's very own bread",
    price: 490,
    img: "./images/item-8.jpeg",
  },
  {
    id: 9,
    name: "French Toast",
    desc: "Crispy * gooney French toast made with chaaye khana's very own bread",
    price: 490,
    img: "./images/item-9.jpeg",
  },
  {
    id: 10,
    name: "French Toast",
    desc: "Crispy * gooney French toast made with chaaye khana's very own bread",
    price: 490,
    img: "./images/item-10.jpeg",
  },
];
export default menu;
